packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.90.2
  "@trpc/client": ^11.6.0
  "@trpc/server": ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  "@eslint/js": ^9.35.0
  eslint: ^9.37.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.14
  "@tailwindcss/postcss": ^4.1.13
  typescript: ^5.9.3
  zod: ^4.1.5

catalogs:
  react19:
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

linkWorkspacePackages: true